[package]
name = "pinapod"
version = "0.3.2"
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
description = "Zero-copy pod types with derive macros. Alignment-1 representations for zero-overhead data access."

[lints]
workspace = true

[features]
default = []
fixed = ["dep:fixed"]
kani = []
wincode = ["dep:wincode"]
solana-address = ["dep:solana-address"]
solana-program-error = ["dep:solana-program-error"]

[dependencies]
fixed = { workspace = true, optional = true }
pinapod-derive = { workspace = true }
solana-address = { version = ">= 2.2, <2.7", optional = true, features = ["copy"] }
solana-program-error = { version = ">=3.0, <4.0", default-features = false, optional = true }
wincode = { version = "0.5.5", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.5.1"
pinapod_previous = { package = "pinapod", version = "0.1.0", git = "https://github.com/pina-rs/pinapod.git", rev = "71ad8bee53e3e6939fe14760e539942d0f1bdd77" }
stats_alloc = "0.1.10"
trybuild = "1.0.111"
zeropod = { version = "0.3.5", git = "https://github.com/blueshift-gg/zeropod.git", rev = "78e6e5f4b515e85999bcc719eb8db59d3ca11b13" }

[[bench]]
name = "api_comparison"
harness = false
