[package]
name = "pinapod"
version.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Zero-copy pod types with derive macros. Alignment-1 representations for zero-overhead data access."

[lints]
workspace = true

[features]
default = []
fixed = ["dep:fixed"]
floats = []
kani = []
wincode = ["dep:wincode"]
solana-address = ["dep:solana-address"]
solana-program-error = ["dep:solana-program-error"]

[dependencies]
fixed = { workspace = true, optional = true, default-features = true }
pinapod-derive = { workspace = true }
solana-address = { optional = true, features = ["copy"], workspace = true, default-features = true }
solana-program-error = { default-features = false, optional = true, workspace = true }
wincode = { default-features = false, features = ["derive"], optional = true, workspace = true }

[dev-dependencies]
criterion = { workspace = true, default-features = true }
pinapod_previous = { package = "pinapod", version = "0.1.0", git = "https://github.com/pina-rs/pinapod.git", rev = "71ad8bee53e3e6939fe14760e539942d0f1bdd77" }
stats_alloc = { workspace = true, default-features = true }
trybuild = { workspace = true, default-features = true }
zeropod = { workspace = true, default-features = true }

[[bench]]
name = "api_comparison"
harness = false
