[graph]
all-features = true

[advisories]
db-path = "target/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db.git"]

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
]
confidence-threshold = 0.8

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
